.PHONY: clean All

All:
	@echo "----------Building project:[ Namespaces - Debug ]----------"
	@cd "Namespaces" && "$(MAKE)" -f  "Namespaces.mk"
clean:
	@echo "----------Cleaning project:[ Namespaces - Debug ]----------"
	@cd "Namespaces" && "$(MAKE)" -f  "Namespaces.mk" clean
