/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EuiStockPrice {
    }
}
declare global {
    interface HTMLEuiStockPriceElement extends Components.EuiStockPrice, HTMLStencilElement {
    }
    var HTMLEuiStockPriceElement: {
        prototype: HTMLEuiStockPriceElement;
        new (): HTMLEuiStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "eui-stock-price": HTMLEuiStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface EuiStockPrice {
    }
    interface IntrinsicElements {
        "eui-stock-price": EuiStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "eui-stock-price": LocalJSX.EuiStockPrice & JSXBase.HTMLAttributes<HTMLEuiStockPriceElement>;
        }
    }
}
