/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EuiSpinner {
    }
    interface EuiStockFinder {
    }
    interface EuiStockPrice {
        "stockSymbol": string;
    }
}
export interface EuiStockFinderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEuiStockFinderElement;
}
declare global {
    interface HTMLEuiSpinnerElement extends Components.EuiSpinner, HTMLStencilElement {
    }
    var HTMLEuiSpinnerElement: {
        prototype: HTMLEuiSpinnerElement;
        new (): HTMLEuiSpinnerElement;
    };
    interface HTMLEuiStockFinderElement extends Components.EuiStockFinder, HTMLStencilElement {
    }
    var HTMLEuiStockFinderElement: {
        prototype: HTMLEuiStockFinderElement;
        new (): HTMLEuiStockFinderElement;
    };
    interface HTMLEuiStockPriceElement extends Components.EuiStockPrice, HTMLStencilElement {
    }
    var HTMLEuiStockPriceElement: {
        prototype: HTMLEuiStockPriceElement;
        new (): HTMLEuiStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "eui-spinner": HTMLEuiSpinnerElement;
        "eui-stock-finder": HTMLEuiStockFinderElement;
        "eui-stock-price": HTMLEuiStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface EuiSpinner {
    }
    interface EuiStockFinder {
        "onEuiSymbolSelected"?: (event: EuiStockFinderCustomEvent<string>) => void;
    }
    interface EuiStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "eui-spinner": EuiSpinner;
        "eui-stock-finder": EuiStockFinder;
        "eui-stock-price": EuiStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "eui-spinner": LocalJSX.EuiSpinner & JSXBase.HTMLAttributes<HTMLEuiSpinnerElement>;
            "eui-stock-finder": LocalJSX.EuiStockFinder & JSXBase.HTMLAttributes<HTMLEuiStockFinderElement>;
            "eui-stock-price": LocalJSX.EuiStockPrice & JSXBase.HTMLAttributes<HTMLEuiStockPriceElement>;
        }
    }
}
