/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EuiSideDrawer {
        "euititle": string;
        "open": () => Promise<void>;
        "opened": boolean;
    }
}
declare global {
    interface HTMLEuiSideDrawerElement extends Components.EuiSideDrawer, HTMLStencilElement {
    }
    var HTMLEuiSideDrawerElement: {
        prototype: HTMLEuiSideDrawerElement;
        new (): HTMLEuiSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "eui-side-drawer": HTMLEuiSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface EuiSideDrawer {
        "euititle"?: string;
        "opened"?: boolean;
    }
    interface IntrinsicElements {
        "eui-side-drawer": EuiSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "eui-side-drawer": LocalJSX.EuiSideDrawer & JSXBase.HTMLAttributes<HTMLEuiSideDrawerElement>;
        }
    }
}
