.PHONY: clean All

All:
	@echo "----------Building project:[ Excercise1 - Debug ]----------"
	@cd "Excercise1" && "$(MAKE)" -f  "Excercise1.mk"
clean:
	@echo "----------Cleaning project:[ Excercise1 - Debug ]----------"
	@cd "Excercise1" && "$(MAKE)" -f  "Excercise1.mk" clean
