/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EclSiteDrawer {
        "title": string;
    }
}
declare global {
    interface HTMLEclSiteDrawerElement extends Components.EclSiteDrawer, HTMLStencilElement {
    }
    var HTMLEclSiteDrawerElement: {
        prototype: HTMLEclSiteDrawerElement;
        new (): HTMLEclSiteDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "ecl-site-drawer": HTMLEclSiteDrawerElement;
    }
}
declare namespace LocalJSX {
    interface EclSiteDrawer {
        "title"?: string;
    }
    interface IntrinsicElements {
        "ecl-site-drawer": EclSiteDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ecl-site-drawer": LocalJSX.EclSiteDrawer & JSXBase.HTMLAttributes<HTMLEclSiteDrawerElement>;
        }
    }
}
